### ISSUE TITLE
Proposal: Improve metrics collector situation

### ISSUE THREAD

**Issue by dmke** [ffddorf/unms-exporter#28]
# Overview

This issue discusses two closely related issues:

1. Prometheus' request context is not inherited/re-used by UNMS API client.
2. The UNMS metrics contain metrics about the collector itself.

These issues arose when working on #23, where I needed to bump the UNMS API request timeout from 5 to 30s. This however is guess work, as the "correct" timeout value heavily depends on the number of devices in your UNMS instance.

## Re-use HTTP request context in UNMS API client

It would be nice, if the `(*Exporter).collectImpl()` method (and `(*Exporter).fetchDeviceData()`, introduced in #22) could inherit and re-use the request context available in the handler (i.e. `(*http.Request).Context()`).

This allows the HTTP client (i.e. Prometheus) to abort the request, which in turn would stop all pending UNMS API requests (they will fail because the inherited context is already cancelled). It also removes the guesswork involved in choosing a "correct" timeout value.

However, since the Prometheus `prometheus.Collector` interface predates Go's `context` package, it is not easy to pass the request context down to the collector. One way to work around this issue, is to create a new `prometheus.Registry` in the HTTP handler and register a new Collector containing the context:

```go
// omitting error handling
handler := func(w http.RequestWriter, r *http.Request) {
  target := r.URL.Query().Get("target")

  if instance, ok := targets[target]; ok {
    reg := prometheus.NewPedanticRegistry()
    reg.MustRegister(&contextWrapper{instance, r.Context()})
    promhttp.HandlerFor(reg, promhttp.HandlerOpts{
      ErrorLog: log,
    }).Serve(w, r)
    return
  }
}
```

<details><summary>This requires a few additions/changes</summary>

A new `contextWrapper` type (bringing the `context.Context` into the `Exporter` struct itself is not a good idea, because that requires getting rid of their internal metrics).

```go
type contextWrapper struct {
  instance *Exporter
  ctx      context.Context
}

func (cw *contextWrapper) Describe(out chan<- *prom.Desc) {
  cw.instance.Describe(out)
}

func (w *contextWrapper) Collect(out chan<- prom.Metric) {
  cw.instance.CollectWithContext(cw.ctx, out)
}
```

Some changes to the `Exporter` struct:

```go
// Keep prometheus.Collector interface intact (optional). Just pick
// a default timeout and pass it down.
func (e *Exporter) Collect(out chan<- prom.Metric) {
  ctx, cancel := context.WithTimeout(context.Backround(), 30*time.Second)
  defer cancel()

  e.CollectWithContext(ctx, out)
}

func (e *Exporter) Collect(ctx context.Context, out chan<- prom.Metric) {
  // fetch data from UNMS API
}
```

</details>

## Untangle Exporter and UNMS metrics

The current registries contain both the `prometheus.NewBuildInfoCollector()` and `prometheus.NewGoCollector()` which yield (almost) duplicate data if you have multiple UNMS instances configured.

I'd like to take the opportunity to move them out of the UNMS metrics and into a separate exporter metrics set, and apply some common patterns found on other exporters:

- `/metrics` would yield build info and Go metrics (`go_info`, `go_gc_*`, et.al.)
- `/metrics?target=name` would yield *only* the UNMS data, as described in the README. 
- `/` would return a simple HTML page listing the available instances, and linking to their metrics endpoint

<details><summary>For this the Prometheus scrape configuration will need an update.</summary>

```yml
scrape_configs:
- job_name: exporters
  static_configs:
    - exporter.example.org:9100 # node exporter
    - exporter.example.org:9806 # UNMS exporter
    - ...

- job_name: unms_exporter
  # for a static target "unms.example.org", rewrite it to
  # "exporter.example.org:9806/metrics?target=unms.example.org",
  # but keep "unms.example.org" as instance label
  relabel_configs:
    - source_labels: [__address__]
      target_label: instance
    - source_labels: [__address__]
      target_label: __param_target
    - replacement: 'exporter.example.org:9806'
      target_label: __address__
  static_configs:
    - targets:
      - my-unms-instance.example.org
```

</details>

I've implemented this pattern successfully in the past (our [`cambium-exporter`](https://github.com/digineo/cambium-exporter) and [`unifi-sdn-exporter`](https://github.com/digineo/unifi-sdn-exporter) work in a similar way). So far, I've not encountered any issues.

## Feedback wanted

Before I start on this, I'd like to gather some feedback, including, but not limited to:

- Would you be willing to accept a PR implementing this? These changes will undoubtedly cause work on your infrastructure (reconfigure Prometheus, maybe update Grafana dashboards).
- Should I provide a single or multiple PRs? (I don't think separating this into multiple PRs would make much sense, however I'd be OK with putting in the extra work).
