### ISSUE TITLE
Token environment variable not picked up

### ISSUE THREAD

**Issue by southerngrampiansshirecouncil** [ffddorf/unms-exporter#66]
When trying to deploy the exporter via docker compose, the token environmental token is not getting picked up.
```
time="2023-01-04T00:54:51Z" level=fatal msg="invalid config" error="No token configured"
  -c, --config string   Config file to use
  -l, --listen string   Address for the exporter to listen on (default "[::]:9806")
```
This is using the below compose file.
```
version: '3.7'
services:
  unms-exporter:
    image: quay.io/ffddorf/unms-exporter
    container_name: unms-exporter
    environment:
      - UNMS_EXPORTER_TOKEN="instance.unmsapp.com=token"
      - TZ=Australia/Melbourne
    ports:
      - 9806:9806
    restart: unless-stopped
```
