### ISSUE TITLE
providing podman-compose.yaml

### ISSUE THREAD

**Issue by LeifSec** [ffddorf/unms-exporter#92]
It would be helpful to have a working `podman-compose.yaml` 

It started with 

```
version: 3.7 

services:
     unms-exporter:
         image: quay.io/ffddorf/unms-exporter
         conateiner_name: unms-exporter
         command: /usr/local/bin/umns-exporter --config /config.yaml
         volumens:
             - /home/pi/config.yaml:/config.yaml
 ```
